version: "3"

services:

  postgresql:
    container_name: postgresql
    image: 'bitnami/postgresql:14'
    restart: always
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: to_do_list
    ports:
      - 5432:5432
    networks:
      - net
    volumes:
      - postgresql-persistence:/bitnami/postgresql
  adonis-app:
    container_name: adonis-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3333:3333
    networks:
      - net
    depends_on:
      - postgresql
    environment:
      PG_HOST: postgresql


volumes:
  postgresql-persistence:

networks:
  net: